---
- name: Setup server
  hosts: all
  remote_user: '{{ provision_username }}'
  become: yes
  vars_files:
    - vars.yaml
  handlers:
    - name: reload firewall
      become: yes
      service:
        name: nftables
        state: reloaded
      register: nftables_reload
      failed_when:
        - "'status' not in nftables_reload"
        - not (msg is search("Could not find requested service"))
      listen: "reload firewall"
  gather_facts: no # Don't gather facts until we know which user we can log in as
  roles:
    - { role: setup,    tags: ['setup']                                         }
    - { role: firewall, tags: ['firewall']                                      }
    - { role: caddy,    tags: ['caddy']                                         }
    - { role: dovecot,  tags: ['dovecot']                                       }
    - { role: dotfiles, tags: ['dotfiles'], when: setup_dotfiles|default(false) }
...
